# Dev Session Buddy Configuration Template
# Minimal Framework-Agnostic Template

name: "Project Name"
framework: minimal
preset: minimal
version: 0.1.0

# Development environment requirements
requirements:
  node: ">=16.0.0"
  npm: ">=8.0.0"

# Development scripts
scripts:
  start: ./session-start.sh
  test: npm test

# Development tools configuration
tools:
  git:
    hooks:
      pre-commit: npm test
  editor:
    formatOnSave: true
    rulers: [80, 100]
    tabSize: 2

# Project standards
standards:
  commits:
    conventional: true
    scopes: []
  testing:
    coverage: 80
    frameworks: []
  documentation:
    required: true
    locations:
      - README.md
      - docs/
  code:
    style: standard
    maxLineLength: 100
