name: Dev Session Buddy
title: Dev Session Buddy - Your AI-Powered Development Companion
description: Standardize development session workflows and improve collaboration between developers and AI assistants
url: https://codevalve.github.io
baseurl: /dev-session-buddy
permalink: pretty
